In [1]:
import pandas as pd
import statsmodels.api as sm
import scipy.stats as stats
import numpy as np


/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


# Cutlets

In [2]:
cutlets=pd.read_csv("/content/Cutlets.csv")

here the null hypotheses H0: both the units produce cutlets of nearly the same diameter size.

alternate hypothesis Ha: there is significance difference between the diameter size of the cultets from the two units

In [4]:
cutlets

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [5]:
#calculating the pvalue
pvalue=stats.ttest_ind(cutlets['Unit A'],cutlets['Unit B'],)[1]
print(pvalue)

0.4722394724599501


In [7]:
alpha=0.05/2 #as it is a two tailed test
if pvalue <= alpha:
  print('We are rejecting the null hypothesis, there is significance difference between the diameter of the cutlets from the two units')
else:
  print('We fail to reject the null hypothesis, that is, the diameter of cutlets from the two units are same')

We fail to reject the null hypothesis, that is, the diameter of cutlets from the two units are same


# Turn Around Time

In [8]:
tat=pd.read_csv("/content/LabTAT.csv")

In [10]:
tat.head()


Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [11]:
tat.isnull().sum() #no null points

Laboratory 1    0
Laboratory 2    0
Laboratory 3    0
Laboratory 4    0
dtype: int64

In [13]:
pvalue_tat=stats.f_oneway(tat['Laboratory 1'],tat['Laboratory 2'],tat['Laboratory 3'],tat['Laboratory 4'])[1]
pvalue_tat

2.1156708949992414e-57

In [15]:
alpha_tat=0.05
if pvalue_tat <= alpha_tat:
  print('The null hypothesis is rejected, all the laboratories have different average TAT scores')
else:
  print('The null hypothesis is accepted(fail to reject), all the average TAT scores from the four laboratories are equal')

The null hypothesis is rejected, all the laboratories have different average TAT scores


# Sales

In [24]:
sales=pd.read_csv("/content/BuyerRatio.csv", index_col=0)

In [25]:
#considering the data given in the datasheet
sales

East  West  North  South
Observed Values                          
Males              50   142    131     70
Females           435  1523   1356    750

In [26]:
table=sales.values #converting to array

In [27]:
table

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [38]:
stats.chi2_contingency(table)

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [40]:
observed=np.array([  50,  142,  131,   70, 435, 1523, 1356,  750])
expected=np.array([  42.76531299,  146.81287862,  131.11756787,   72.30424052, 442.23468701, 1518.18712138, 1355.88243213,  747.69575948])

In [41]:
pvalue_sales=stats.chisquare(observed,expected,ddof=3)[1]
print(pvalue_sales)

0.8095206646905712


In [43]:
alpha_sales=0.05
if pvalue_sales <= alpha_sales:
  print('The null hypothesis must be rejected, the male and female data are dependent')
else:
  print('The null hypothesis is accepted(fail to reject), both the male and female data are independent')

The null hypothesis is accepted(fail to reject), both the male and female data are independent


# TeleCall

In [44]:
tele=pd.read_csv('/content/Costomer+OrderForm.csv')

In [45]:
tele.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [46]:
print(tele['Phillippines'].value_counts(), '\n', tele['Indonesia'].value_counts(),'\n', tele['Malta'].value_counts(),'\n', tele['India'].value_counts())

Error Free    271
Defective      29
Name: Phillippines, dtype: int64 
 Error Free    267
Defective      33
Name: Indonesia, dtype: int64 
 Error Free    269
Defective      31
Name: Malta, dtype: int64 
 Error Free    280
Defective      20
Name: India, dtype: int64


In [47]:
input_table=[[271, 267, 269, 280],
             [29, 33, 31, 20]]
print(input_table)

[[271, 267, 269, 280], [29, 33, 31, 20]]


In [48]:
stats.chi2_contingency(input_table)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [49]:
observed_tele=np.array([271, 267, 269, 280, 29, 33, 31, 20])
expected_tele=np.array([271.75, 271.75, 271.75, 271.75, 28.25,  28.25,  28.25,  28.25])

In [50]:
pvalue_tele=stats.chisquare(observed_tele,expected_tele,ddof=3)[1]
print(pvalue_tele)

0.4254298144535761


In [52]:
alpha_tele=0.05
if pvalue_tele <= alpha_tele:
  print('We reject the null hypothesis, the defective % varies with the centres ')
else:
  print('We accept the null hypothesis(fail to reject), the defective % is the same for all the centres')

We accept the null hypothesis(fail to reject), the defective % is the same for all the centres
